# Generated by Django 3.2.4 on 2021-06-07 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projectResponsibles', '0001_initial'),
        ('projectTypes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=100)),
                ('active', models.BooleanField(default=True)),
                ('project_responsible', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='projectResponsibles.projectresponsible')),
                ('project_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='projectTypes.projecttype')),
            ],
        ),
    ]
