# Generated by Django 3.2.4 on 2021-06-08 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectTypes', '0001_initial'),
        ('projectResponsibles', '0002_alter_projectresponsible_full_name'),
        ('Projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='active',
            field=models.BooleanField(default=True, help_text='is the project still active, or not'),
        ),
        migrations.AlterField(
            model_name='project',
            name='code',
            field=models.CharField(max_length=10, verbose_name='Project Code'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.CharField(max_length=100, verbose_name='Project Description'),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Project Name'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_responsible',
            field=models.ForeignKey(help_text='choose the person who is responsible for this project', null=True, on_delete=django.db.models.deletion.SET_NULL, to='projectResponsibles.projectresponsible', verbose_name='Project Responsible'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_type',
            field=models.ForeignKey(help_text='choose the type of project (Dx, SpotID, etc.)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='projectTypes.projecttype', verbose_name='Project Type'),
        ),
    ]
