# Generated by Django 3.2.4 on 2021-06-08 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectResponsibles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectresponsible',
            name='full_name',
            field=models.CharField(max_length=100, verbose_name='Full Name'),
        ),
    ]
